# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 腾讯云轻量应用服务器流量告警

on:
  workflow_dispatch:
  push:
    branches: 
    - main
  schedule:
    - cron: "0 2 * * *"


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.13
      uses: actions/setup-python@main
      with:
        python-version: 3.13
    - name: Install tencentcloud-sdk-python
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: "run LH.py"
      env:
        SecretId: ${{secrets.SecretId}}
        SecretKey: ${{secrets.SecretKey}}
      run: |
        python LH.py
